
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-frobs-danielfbm-github-io-v1alpha1-frobber
  failurePolicy: Fail
  name: mfrobber.kb.io
  rules:
  - apiGroups:
    - frobs.danielfbm.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frobbers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-frobs-danielfbm-github-io-v1alpha1-frobber
  failurePolicy: Fail
  name: vfrobber.kb.io
  rules:
  - apiGroups:
    - frobs.danielfbm.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frobbers
