# permissions for end users to view frobbers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frobber-viewer-role
rules:
- apiGroups:
  - frobs.danielfbm.github.io
  resources:
  - frobbers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frobs.danielfbm.github.io
  resources:
  - frobbers/status
  verbs:
  - get
